[Improvement] hivemq extension sdk version as property
hivemq/hivemq-maven-extension-archetype pull request #20
Opened 2021-06-10 10:45 UTC by YannickWeber

2021-06-11 20:02 UTC, SgtSilvio commented on README.adoc
> +mvn archetype:generate -DarchetypeGroupId=com.hivemq -DarchetypeArtifactId=hivemq-extension-archetype -DhivemqExtensionSdkVersion=4.6.3
we should probably still define archetypeVersion

2021-06-11 20:02 UTC, SgtSilvio approved these changes

2021-06-24 09:51 UTC, DC2-DanielKrueger commented on README.adoc
> +mvn archetype:generate -DarchetypeGroupId=com.hivemq -DarchetypeArtifactId=hivemq-extension-archetype -DarchetypeVersion=4.7.0 -DhivemqExtensionSdkVersion=4.6.2
i think we said in the standup that we can not make anything publish that has 4.7.0 in its name?

2021-06-24 09:51 UTC, DC2-DanielKrueger commented on pom.xml
> +    <version>4.7.0</version>
sure? I think we said we use another version in the standup iirc

2021-06-24 09:53 UTC, DC2-DanielKrueger requested changes
version is not ok i think

2021-06-24 13:06 UTC, DC2-DanielKrueger approved these changes

2021-06-24 13:06 UTC, SgtSilvio approved these changes

2021-06-24 13:48 UTC, merged